# Generated by Django 4.0.3 on 2022-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='final_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
