# Generated by Django 4.0.3 on 2022-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_final_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
